### ISSUE TITLE
Task :react-native-screens:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by frusty84** [HarishJangra/react-native-easy-starter#38]
Hello.
Hope someone can help me. I have problems launching the apk.
I have tried to solve it with some solution that is detailed here but I have not achieved anything. I have done gradle clean and neither.
Thanks.

C:\Users\AGUS\Desktop\workreap-app>react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets
-dest android/app/src/main/res
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
(node:5920) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Loading dependency graph...warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
Loading dependency graph, done.
Loading dependency graph...info Writing bundle output to:, android/app/src/main/assets/index.android.bundle
info Done writing bundle output
info Copying 69 asset files
info Done copying assets

C:\Users\AGUS\Desktop\workreap-app>react-native run-android --variant=release
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-background-downloader (to unlink run: "react-native unlink react-native-background-downloader")
  - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")
  - react-native-vector-icons (to unlink run: "react-native unlink react-native-vector-icons")
  - rn-range-slider (to unlink run: "react-native unlink rn-range-slider")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it wi
ll be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
(node:6216) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Jetifier found 1181 file(s) to forward-jetify. Using 2 workers...
info Starting JS server...
info Installing the app...

> Task :@react-native-community_toolbar-android:compileReleaseJavaWithJavac

> Task :react-native-background-downloader:compileReleaseJavaWithJavac

> Task :react-native-gesture-handler:compileReleaseJavaWithJavac

> Task :react-native-image-crop-picker:compileReleaseJavaWithJavac

> Task :react-native-maps:compileReleaseJavaWithJavac

> Task :react-native-reanimated:compileReleaseJavaWithJavac

> Task :react-native-screens:compileReleaseJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
180 actionable tasks: 180 executed
Note: C:\Users\AGUS\Desktop\workreap-app\node_modules\@react-native-community\toolbar-android\android\src\main\java\com\reactnativecommunity\toolbarandroid\ReactToolbar.java uses or
 overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-background-downloader\android\src\main\java\com\eko\RNBackgroundDownloaderModule.java uses unchecked or unsafe ope
rations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java us
es or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:26: error: cannot find symbol
import com.facebook.react.views.text.ReactTypefaceUtils;
                                    ^
  symbol:   class ReactTypefaceUtils
  location: package com.facebook.react.views.text
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:247: error: cannot find symbol
        Typeface titleTypeface = ReactTypefaceUtils.applyStyles(
                                 ^
  symbol:   variable ReactTypefaceUtils
  location: class ScreenStackHeaderConfig
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:377: error: cannot find symbol
    mTitleFontWeight = ReactTypefaceUtils.parseFontWeight(fontWeightString);
                       ^
  symbol:   variable ReactTypefaceUtils
  location: class ScreenStackHeaderConfig
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 42s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development
-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installRelease -PreactNativeDevServerPort=8081
Note: C:\Users\AGUS\Desktop\workreap-app\node_modules\@react-native-community\toolbar-android\android\src\main\java\com\reactnativecommunity\toolbarandroid\ReactToolbar.java uses or
 overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-background-downloader\android\src\main\java\com\eko\RNBackgroundDownloaderModule.java uses unchecked or unsafe ope
rations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java us
es or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:26: error: cannot find symbol
import com.facebook.react.views.text.ReactTypefaceUtils;
                                    ^
  symbol:   class ReactTypefaceUtils
  location: package com.facebook.react.views.text
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:247: error: cannot find symbol
        Typeface titleTypeface = ReactTypefaceUtils.applyStyles(
                                 ^
  symbol:   variable ReactTypefaceUtils
  location: class ScreenStackHeaderConfig
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:377: error: cannot find symbol
    mTitleFontWeight = ReactTypefaceUtils.parseFontWeight(fontWeightString);
                       ^
  symbol:   variable ReactTypefaceUtils
  location: class ScreenStackHeaderConfig
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 42s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:15)
    at runOnAllDevices (C:\Users\AGUS\Desktop\workreap-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (C:\Users\AGUS\Desktop\workreap-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at C:\Users\AGUS\Desktop\workreap-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (C:\Users\AGUS\Desktop\workreap-app\node_modules\@react-native-community\cli\build\cliEntry.js:160:7)

C:\Users\AGUS\Desktop\workreap-app>react-native run-android --variant=release
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-background-downloader (to unlink run: "react-native unlink react-native-background-downloader")
  - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")
  - react-native-vector-icons (to unlink run: "react-native unlink react-native-vector-icons")
  - rn-range-slider (to unlink run: "react-native unlink rn-range-slider")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it wi
ll be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
(node:7316) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Jetifier found 1181 file(s) to forward-jetify. Using 2 workers...
info Starting JS server...
info Installing the app...

> **Task :react-native-screens:compileReleaseJavaWithJavac FAILED**

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
179 actionable tasks: 2 executed, 177 up-to-date
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:26: error: cannot find symbol
import com.facebook.react.views.text.ReactTypefaceUtils;
                                    ^
  symbol:   class ReactTypefaceUtils
  location: package com.facebook.react.views.text
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:247: error: cannot find symbol
        Typeface titleTypeface = ReactTypefaceUtils.applyStyles(
                                 ^
  symbol:   variable ReactTypefaceUtils
  location: class ScreenStackHeaderConfig
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:377: error: cannot find symbol
    mTitleFontWeight = ReactTypefaceUtils.parseFontWeight(fontWeightString);
                       ^
  symbol:   variable ReactTypefaceUtils
  location: class ScreenStackHeaderConfig
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development
-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installRelease -PreactNativeDevServerPort=8081
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:26: error: cannot find symbol
import com.facebook.react.views.text.ReactTypefaceUtils;
                                    ^
  symbol:   class ReactTypefaceUtils
  location: package com.facebook.react.views.text
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:247: error: cannot find symbol
        Typeface titleTypeface = ReactTypefaceUtils.applyStyles(
                                 ^
  symbol:   variable ReactTypefaceUtils
  location: class ScreenStackHeaderConfig
C:\Users\AGUS\Desktop\workreap-app\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:377: error: cannot find symbol
    mTitleFontWeight = ReactTypefaceUtils.parseFontWeight(fontWeightString);
                       ^
  symbol:   variable ReactTypefaceUtils
  location: class ScreenStackHeaderConfig
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:15)
    at runOnAllDevices (C:\Users\AGUS\Desktop\workreap-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (C:\Users\AGUS\Desktop\workreap-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at C:\Users\AGUS\Desktop\workreap-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (C:\Users\AGUS\Desktop\workreap-app\node_modules\@react-native-community\cli\build\cliEntry.js:160:7)

C:\Users\AGUS\Desktop\workreap-app>npm -v
7.10.0

C:\Users\AGUS\Desktop\workreap-app>react-native -v
react-native-cli: 2.0.1
react-native: 0.60.5

C:\Users\AGUS\Desktop\workreap-app>gradle -v

------------------------------------------------------------
Gradle 7.0
------------------------------------------------------------

Build time:   2021-04-09 22:27:31 UTC
Revision:     d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0-282 (Oracle Corporation 25.71-b08)
OS:           Windows 10 10.0 amd64

**Comment by mayank-budhiraja** [comment]
Hello @frusty84 - Add keys to the gradle.properties
